//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Backoffice_delete
    {
        public string bd_instdesc { get; set; }
        public string bd_trx_type { get; set; }
        public System.DateTime bd_trx_date { get; set; }
        public string bd_client_id { get; set; }
        public string bd_isin { get; set; }
        public Nullable<decimal> bd_qty { get; set; }
        public string bd_market_type { get; set; }
        public string bd_settlement { get; set; }
        public System.DateTime bd_execution_date { get; set; }
        public string bd_other_dp_id { get; set; }
        public string bd_other_client_id { get; set; }
        public string bd_other_cmbp_id { get; set; }
        public string bd_internal_refno { get; set; }
        public string bd_other_markettype { get; set; }
        public string bd_other_settle_no { get; set; }
        public string bd_lock_release_code { get; set; }
        public Nullable<System.DateTime> bd_lock_release_date { get; set; }
        public string bd_cc_id1 { get; set; }
        public string bd_cc_id2 { get; set; }
        public string bd_status { get; set; }
        public string bd_trx_allow { get; set; }
        public int bd_pri_key { get; set; }
        public string bd_authcode1 { get; set; }
        public string bd_authuserid1 { get; set; }
        public Nullable<System.DateTime> bd_authdt1 { get; set; }
        public string bd_authcode2 { get; set; }
        public string bd_authuserid2 { get; set; }
        public Nullable<System.DateTime> bd_authdt2 { get; set; }
        public string bd_branchcd { get; set; }
        public string bd_branchbatchcd { get; set; }
        public string mkrid { get; set; }
        public Nullable<System.DateTime> mkrdt { get; set; }
        public string bd_authcode3 { get; set; }
        public string bd_authuserid3 { get; set; }
        public Nullable<System.DateTime> bd_authdt3 { get; set; }
        public string bd_authremarks { get; set; }
        public Nullable<decimal> bd_scrollno { get; set; }
        public Nullable<int> bd_totalcertificate { get; set; }
        public string bd_computername { get; set; }
        public string mkrtm { get; set; }
        public decimal bd_unique { get; set; }
        public string mkrtmold { get; set; }
        public string mkridold { get; set; }
        public string bd_authtm1 { get; set; }
        public string bd_authtm2 { get; set; }
        public string bd_authtm3 { get; set; }
        public Nullable<System.DateTime> mkrdtold { get; set; }
    }
}
