//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Backoffice_audit
    {
        public string ba_trx_type { get; set; }
        public int ba_pri_key { get; set; }
        public string ba_branchcd { get; set; }
        public string ba_field { get; set; }
        public string ba_oldvalue { get; set; }
        public string ba_newvalue { get; set; }
        public string mkrid { get; set; }
        public System.DateTime mkrdt { get; set; }
        public string ba_computername { get; set; }
        public string mkrtm { get; set; }
        public decimal ba_delunique { get; set; }
        public string mkrtmold { get; set; }
        public string mkridold { get; set; }
        public Nullable<System.DateTime> mkrdtold { get; set; }
    }
}
