//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Backoffice_balance
    {
        public string bc_cmcd { get; set; }
        public Nullable<decimal> bc_ledger { get; set; }
        public string bc_mkrid { get; set; }
        public string bc_mkrdt { get; set; }
    }
}
