//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank_master
    {
        public string bk_id { get; set; }
        public string bk_name { get; set; }
        public string bk_branch { get; set; }
        public string bk_ifsccode { get; set; }
        public string bk_micr { get; set; }
        public string bk_add1 { get; set; }
        public string bk_add2 { get; set; }
        public string bk_add3 { get; set; }
        public string bk_add4 { get; set; }
        public string bk_pin { get; set; }
        public string bk_filler1 { get; set; }
        public string bk_filler2 { get; set; }
        public string bk_status { get; set; }
        public string bk_filler3 { get; set; }
    }
}
