//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bpmaster
    {
        public string bp_id { get; set; }
        public string bp_role { get; set; }
        public string bp_add1 { get; set; }
        public string bp_add2 { get; set; }
        public string bp_add3 { get; set; }
        public string bp_add4 { get; set; }
        public string bp_pin { get; set; }
        public string bp_phone { get; set; }
        public string bp_fax { get; set; }
        public string bp_assd_cc_id { get; set; }
        public string bp_assd_dp_id { get; set; }
        public string bp_assd_cc_cmid { get; set; }
        public string bp_category { get; set; }
        public string bp_name { get; set; }
        public string bp_stat { get; set; }
    }
}
