//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch_master
    {
        public string bm_branchcd { get; set; }
        public string bm_branchname { get; set; }
        public string bm_contact { get; set; }
        public string bm_add1 { get; set; }
        public string bm_add2 { get; set; }
        public string bm_add3 { get; set; }
        public string bm_city { get; set; }
        public string bm_pin { get; set; }
        public string bm_phone { get; set; }
        public string bm_fax { get; set; }
        public string bm_email { get; set; }
        public string bm_allow { get; set; }
        public Nullable<decimal> bm_batchno { get; set; }
        public string bm_ip_add { get; set; }
        public string bm_dialup { get; set; }
        public string bm_server { get; set; }
        public string bm_database { get; set; }
        public string bm_dbo { get; set; }
        public string bm_user { get; set; }
        public string bm_pwd { get; set; }
        public string bm_workarea { get; set; }
        public string mkrid { get; set; }
        public Nullable<System.DateTime> mkrdt { get; set; }
        public Nullable<decimal> bm_percentage { get; set; }
        public string bm_flag { get; set; }
        public string bm_authorisation { get; set; }
    }
}
