//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cc_calender
    {
        public string cc_id { get; set; }
        public string cc_mkt_type { get; set; }
        public string cc_settle_no { get; set; }
        public System.DateTime cc_settle_periodfrom { get; set; }
        public System.DateTime cc_settle_periodto { get; set; }
        public System.DateTime cc_nsdl_deadlinedt { get; set; }
        public string cc_nsdl_deadlinett { get; set; }
        public System.DateTime cc_payin_dt { get; set; }
        public System.DateTime cc_payout_dt { get; set; }
    }
}
