//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chequestop
    {
        public string chs_cmcd { get; set; }
        public decimal chs_chqno { get; set; }
        public string chs_chqdate { get; set; }
        public string chs_reference { get; set; }
        public string chs_refdate { get; set; }
        public string chs_status { get; set; }
        public string chs_date { get; set; }
        public short chs_instcd { get; set; }
        public string chs_remark { get; set; }
        public string mkrid { get; set; }
        public string mkrdt { get; set; }
    }
}
