//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chequemaster
    {
        public string chm_cmcd { get; set; }
        public decimal chm_chqno { get; set; }
        public short chm_instcd { get; set; }
        public short chm_booksize { get; set; }
        public string chm_refno { get; set; }
        public Nullable<System.DateTime> chm_refdate { get; set; }
        public string chm_status { get; set; }
        public Nullable<System.DateTime> chm_issuedate { get; set; }
        public string chm_remarks { get; set; }
        public string chm_branchcd { get; set; }
        public string mkrid { get; set; }
        public Nullable<System.DateTime> mkrdt { get; set; }
        public Nullable<decimal> chm_fromno { get; set; }
        public Nullable<decimal> chm_tono { get; set; }
        public string chm_type { get; set; }
    }
}
