//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_master1
    {
        public string cm_brcode { get; set; }
        public string cm_cd { get; set; }
        public string cm_benttype { get; set; }
        public string cm_bensubtype { get; set; }
        public string cm_ben_shortname { get; set; }
        public string cm_ben_acccatorgy { get; set; }
        public string cm_occup { get; set; }
        public string cm_name { get; set; }
        public string cm_filler { get; set; }
        public string cm_fatherhu { get; set; }
        public string cm_add1 { get; set; }
        public string cm_add2 { get; set; }
        public string cm_add3 { get; set; }
        public string cm_add4 { get; set; }
        public string cm_pin { get; set; }
        public string cm_tele1 { get; set; }
        public string cm_fax { get; set; }
        public string cm_sech_name { get; set; }
        public string cm_sech_fathername { get; set; }
        public string cm_thih_name { get; set; }
        public string cm_thih_fathername { get; set; }
        public string cm_bp_id { get; set; }
        public string cm_addperflag { get; set; }
        public Nullable<System.DateTime> cm_opendate { get; set; }
        public string cm_filler1 { get; set; }
        public string cm_firstpanno { get; set; }
        public string cm_secpanno { get; set; }
        public string cm_thirdpanno { get; set; }
        public string cm_nomgur_flag { get; set; }
        public string cm_nomgur_name { get; set; }
        public string cm_dobmin { get; set; }
        public string cm_nomineeadd1 { get; set; }
        public string cm_nomineeadd2 { get; set; }
        public string cm_nomineeadd3 { get; set; }
        public string cm_nomineeadd4 { get; set; }
        public string cm_nomineepin { get; set; }
        public string cm_stainst { get; set; }
        public string cm_rgess { get; set; }
        public string cm_bsda { get; set; }
        public string cm_filler2 { get; set; }
        public string cm_bankifscocde { get; set; }
        public string cm_commdity { get; set; }
        public string cm_bankacttype { get; set; }
        public string cm_bankname { get; set; }
        public string cm_bankadd1 { get; set; }
        public string cm_bankadd2 { get; set; }
        public string cm_bankadd3 { get; set; }
        public string cm_bankadd4 { get; set; }
        public string cm_bankpin { get; set; }
        public string cm_micr { get; set; }
        public string cm_rbi_refno { get; set; }
        public Nullable<System.DateTime> cm_rbi_appdate { get; set; }
        public string cm_sebireg { get; set; }
        public string cm_taxstatus { get; set; }
        public string cm_ben_satus { get; set; }
        public string cm_ben_satatchagecode { get; set; }
        public Nullable<System.DateTime> cm_acc_closuredate { get; set; }
        public string cm_filler3 { get; set; }
        public string cm_corforadd1 { get; set; }
        public string cm_corforadd2 { get; set; }
        public string cm_corforadd3 { get; set; }
        public string cm_corforadd4 { get; set; }
        public string cm_corforpin { get; set; }
        public string cm_corfortele1 { get; set; }
        public string cm_corforfax { get; set; }
        public string cm_minornomineei_ind { get; set; }
        public Nullable<System.DateTime> cm_minornominee_dob { get; set; }
        public string cm_minornomineei_name { get; set; }
        public string cm_minornomineei_add1 { get; set; }
        public string cm_minornomineei_add2 { get; set; }
        public string cm_minornomineei_add3 { get; set; }
        public string cm_minornomineei_add4 { get; set; }
        public string cm_minornomineei_pin { get; set; }
        public string cm_bankactno { get; set; }
        public string cm_email { get; set; }
        public string cm_mobile { get; set; }
        public string cm_filler4 { get; set; }
        public string cm_rtaemai1 { get; set; }
        public string cm_sms { get; set; }
        public string cm_panflag { get; set; }
        public string cm_auth_flag { get; set; }
        public string cm_nonomniee_flag { get; set; }
        public string cm_filler5 { get; set; }
        public string cm_secondemail { get; set; }
        public string cm_second_mobile { get; set; }
        public string cm_filler6 { get; set; }
        public string cm_rtaemail2 { get; set; }
        public string cm_sec_sms { get; set; }
        public string cm_secpan_flag { get; set; }
        public string cm_secauth_flag { get; set; }
        public string cm_filler7 { get; set; }
        public string cm_thirdemail { get; set; }
        public string cm_third_mobile { get; set; }
        public string cm_filler8 { get; set; }
        public string cm_rtaemail3 { get; set; }
        public string cm_thir_sms { get; set; }
        public string cm_thirpan_flag { get; set; }
        public string cm_thirauth_flag { get; set; }
        public string cm_addhar1 { get; set; }
        public string cm_filler9 { get; set; }
        public string cm_addhar2 { get; set; }
        public string cm_filler10 { get; set; }
        public string cm_addhar3 { get; set; }
        public string cm_filler11 { get; set; }
        public string cm_filler12 { get; set; }
        public string cm_brboffcode { get; set; }
        public string cm_groupcd { get; set; }
        public string cm_familycd { get; set; }
        public string cm_introducer { get; set; }
        public string cm_attorney { get; set; }
        public string cm_indicator { get; set; }
        public string cm_add_pref_flag { get; set; }
        public string cm_chgsscheme { get; set; }
        public string cm_billcycle { get; set; }
        public string cm_statements { get; set; }
        public string cm_billflag { get; set; }
        public string cm_billcode { get; set; }
        public string cm_collectioncode { get; set; }
        public Nullable<decimal> cm_allowcredit { get; set; }
        public string cm_upfront { get; set; }
        public Nullable<System.DateTime> cm_lastbill { get; set; }
        public string cm_keepsettlement { get; set; }
        public Nullable<byte> cm_fre_trx { get; set; }
        public Nullable<byte> cm_fre_hold { get; set; }
        public Nullable<byte> cm_fre_bill { get; set; }
        public string cm_blsavingcd { get; set; }
        public Nullable<System.DateTime> cm_amtmntdt { get; set; }
        public Nullable<decimal> cm_updatebal { get; set; }
        public Nullable<decimal> cm_schedule { get; set; }
        public Nullable<decimal> cm_openingbal { get; set; }
        public Nullable<System.DateTime> mkrdt { get; set; }
        public string mkrid { get; set; }
        public string cm_freezeyn { get; set; }
        public string cm_freezereason { get; set; }
        public string cm_PoaForPayin { get; set; }
        public string cm_remissier { get; set; }
        public string cm_remissierscheme { get; set; }
    }
}
