//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instrument_master
    {
        public short im_instcd { get; set; }
        public string im_desc { get; set; }
        public string im_trtype { get; set; }
        public Nullable<int> im_reorderlevel { get; set; }
        public string mkrid { get; set; }
        public string mkrdt { get; set; }
        public string im_defaultyn { get; set; }
    }
}
