//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interdepository
    {
        public string id_instcd { get; set; }
        public System.DateTime id_trxdate { get; set; }
        public string id_trxtype { get; set; }
        public string id_trxflag { get; set; }
        public string id_clientid { get; set; }
        public string id_isin { get; set; }
        public Nullable<decimal> id_qty { get; set; }
        public string id_mkttype { get; set; }
        public string id_settlementno { get; set; }
        public System.DateTime id_executiondate { get; set; }
        public string id_otherclientid { get; set; }
        public string id_otherdpid { get; set; }
        public string id_internalrefno { get; set; }
        public string id_cc_id { get; set; }
        public string id_status { get; set; }
        public string id_allow { get; set; }
        public string id_othersettlement { get; set; }
        public string id_authcode1 { get; set; }
        public string id_authuserid1 { get; set; }
        public Nullable<System.DateTime> id_authdate1 { get; set; }
        public string id_authcode2 { get; set; }
        public string id_authuserid2 { get; set; }
        public Nullable<System.DateTime> id_authdate2 { get; set; }
        public Nullable<int> id_batch_no { get; set; }
        public int id_pri_key { get; set; }
        public string id_branchcd { get; set; }
        public string id_branchbatchcd { get; set; }
        public string mkrid { get; set; }
        public Nullable<System.DateTime> mkrdt { get; set; }
        public string id_authcode3 { get; set; }
        public string id_authuserid3 { get; set; }
        public Nullable<System.DateTime> id_authdt3 { get; set; }
        public string id_authremarks { get; set; }
        public Nullable<decimal> id_scrollno { get; set; }
        public Nullable<decimal> id_dqty { get; set; }
        public Nullable<decimal> id_lotno { get; set; }
        public string id_authtm1 { get; set; }
        public string id_authtm2 { get; set; }
        public string id_authtm3 { get; set; }
        public string mkrtm { get; set; }
        public string id_instreceivemode { get; set; }
        public string id_recoslipyn { get; set; }
        public string id_entrymode { get; set; }
        public string id_remarks { get; set; }
        public string id_CDSLsettlement { get; set; }
    }
}
