//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inward_entry
    {
        public Nullable<decimal> ie_lotno { get; set; }
        public string ie_trxtype { get; set; }
        public string ie_instno { get; set; }
        public string ie_slipno { get; set; }
        public string ie_cmcd { get; set; }
        public Nullable<System.DateTime> ie_dt { get; set; }
        public Nullable<System.DateTime> ie_execdt { get; set; }
        public Nullable<int> ie_nooftrx { get; set; }
        public Nullable<int> ie_noofcert { get; set; }
        public Nullable<int> ie_rejected { get; set; }
        public int ie_scrollno { get; set; }
        public string mkrid { get; set; }
        public Nullable<System.DateTime> mkrdt { get; set; }
        public Nullable<decimal> ie_charge { get; set; }
        public string ie_mode { get; set; }
        public string ie_remark { get; set; }
        public Nullable<decimal> ie_pri_key { get; set; }
        public string ie_branchcd { get; set; }
        public string ie_ref { get; set; }
    }
}
