//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lot_size
    {
        public decimal lz_lotno { get; set; }
        public string lz_type { get; set; }
        public int lz_size { get; set; }
        public string lz_status { get; set; }
        public string mkrid { get; set; }
        public Nullable<System.DateTime> mkrdt { get; set; }
        public string lz_branchcd { get; set; }
    }
}
