//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rate_master
    {
        public string rm_isin_code { get; set; }
        public System.DateTime rm_trx_date { get; set; }
        public decimal rm_rate { get; set; }
    }
}
