//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Security
    {
        public string sc_isincode { get; set; }
        public string sc_nsecurity_code { get; set; }
        public Nullable<int> sc_book_basis { get; set; }
        public string sc_isinname { get; set; }
        public string sc_company_code { get; set; }
        public string sc_company_name { get; set; }
        public string sc_security_type { get; set; }
        public string sc_security_subtype { get; set; }
        public System.DateTime sc_issue { get; set; }
        public Nullable<System.DateTime> sc_maturity_date { get; set; }
        public Nullable<System.DateTime> sc_convert_date { get; set; }
        public Nullable<decimal> sc_face_value { get; set; }
        public Nullable<decimal> sc_convert_amount { get; set; }
        public string sc_agentname { get; set; }
        public string sc_security_status { get; set; }
        public string sc_security_remark { get; set; }
        public string sc_decimal_allow { get; set; }
        public string sc_reg_code { get; set; }
        public string sc_reg_name { get; set; }
        public string sc_bsecd { get; set; }
        public string sc_nsesym { get; set; }
        public string sc_nsesrs { get; set; }
        public string sc_attn { get; set; }
        public string sc_sl_balance { get; set; }
        public Nullable<decimal> sc_rate { get; set; }
        public string sc_rolling { get; set; }
        public string sc_corporateaction { get; set; }
        public string mkrid { get; set; }
        public Nullable<System.DateTime> mkrdt { get; set; }
        public string sc_sector { get; set; }
    }
}
