//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_master
    {
        public short stm_instcd { get; set; }
        public Nullable<short> stm_vmcd { get; set; }
        public string stm_vmrefno { get; set; }
        public string stm_date { get; set; }
        public int stm_fromno { get; set; }
        public int stm_tono { get; set; }
        public short stm_booksize { get; set; }
        public int stm_noofbooks { get; set; }
        public string mkrid { get; set; }
        public string mkrdt { get; set; }
        public string stm_vmtype { get; set; }
        public Nullable<int> stm_bookfromno { get; set; }
        public Nullable<int> stm_booktono { get; set; }
    }
}
