//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sysparameter
    {
        public string sp_parmcd { get; set; }
        public string sp_effdt { get; set; }
        public string sp_name { get; set; }
        public Nullable<decimal> sp_datatype { get; set; }
        public Nullable<decimal> sp_datalen { get; set; }
        public string sp_table { get; set; }
        public string sp_sysvalue { get; set; }
        public string sp_Securedyn { get; set; }
        public string mkrid { get; set; }
        public string mkrdt { get; set; }
    }
}
