//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Used_slip
    {
        public string us_trxtype { get; set; }
        public string us_instcd { get; set; }
        public decimal us_irn { get; set; }
        public string us_clientcd { get; set; }
        public string us_execdt { get; set; }
        public string us_mode { get; set; }
        public string us_remarks { get; set; }
        public string us_archiveyn { get; set; }
        public string us_filler1 { get; set; }
        public string mkrid { get; set; }
        public string mkrdt { get; set; }
        public string mkrtm { get; set; }
    }
}
