//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor_master
    {
        public short vm_cd { get; set; }
        public string vm_name { get; set; }
        public string vm_add1 { get; set; }
        public string vm_add2 { get; set; }
        public string vm_add3 { get; set; }
        public string vm_add4 { get; set; }
        public string vm_pin { get; set; }
        public string vm_tel { get; set; }
        public string vm_email { get; set; }
        public string mkrid { get; set; }
        public string mkrdt { get; set; }
    }
}
